name: deploy-mandarin
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - run: npx webpack
      - name: Init new repo in dist folder and commit generated files
        run: |
          cd dist
          git init
          git add -A
          git config --local user.email "i.deruga@gmail.com"
          git config --local user.name "Igor Deruga"
          git remote add origin https://x-access-token:${{ secrets.MANDARIN_SECRET }}@github.com/ideruga/mandarin-src.git
          git commit -m 'deploy'
          git push --set-upstream origin master
#      - name: Force push to destination branch
#        uses: ad-m/github-push-action@v0.5.0
#        with:
#          github_token: ${{ secrets.MANDARIN_SECRET }}
#          branch: master
#          force: false
#          directory: ./dist
#          repository: mandarin
